title: "Li Jizhong | Embodied Intelligence"
page-top-title: Li Jizhong
top-section-bg-text: Perceive. Remember. Act.
home-subtitle: Li Jizhong&ensp;|&ensp;Embodied Intelligence Researcher
copyright-text: '&copy; Li Jizhong 2026. All Rights Reserved.'
